pagina = open("pagina.html", "w", encoding="utf-8") #r = ler, w = escrever

pagina.write("<!DOCTYPE HTML>\n")
pagina.write("<HTML lang=\"pt-br\">\n")
pagina.write("<HEAD>\n")
pagina.write("<title>Professor Neri - html5</title>\n")
pagina.write("</HEAD>\n")
pagina.write("<BODY>\n")
pagina.write("<h1>Videoaulas neri<h1><br>\n")
pagina.write("7 * 1 = <br>\n")
pagina.write("7 * 2 = <br>\n")
pagina.write("7 * 3 = <br>\n")
pagina.write("7 * 4 = <br>\n")
pagina.write("7 * 5 = <br>\n")
pagina.write("7 * 6 = <br>\n")
pagina.write("7 * 7 = <br>\n")
pagina.write("7 * 8 = <br>\n")
pagina.write("7 * 9 = <br>\n")
pagina.write("<br>Prof Neri Aldoir Neitzke\n")
pagina.write("</BODY>\n")
pagina.write("</HTML>\n")
pagina.flush()
pagina.close()
