nome = input("Digite seu nome: ")
print("Capitalize (primeiro caracter é maiúsculo = ", nome.capitalize())
print("Center: centraliza com espaços em branco = ", nome.center(50))
print("Quantas letras E ele tem no nome: ", nome.count("e"))
print("Retorna True se o nome terminar com us: ", nome.endswith("us"))
print("Find retorna posição de String ", nome.find("n"))
print("Find retorna posição de String ", nome.find("n",1 ))
print("Find retorna posição de String ", nome.find("n", 2, 3))
print("Find retorna posição de String ", nome.index("n"))
print("Find retorna posição de String ", nome.index("y",2))
